apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: versions-explorer
  namespace: admin
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: versions_exporter
      spec:
        containers:
          - name: versions-exporter
            image: harbor.nuglif.net/adminversions_exporter:0.1.0
            env:
              - name: VERSIONS_EXPORTER_LOGLEVEL
                value: debug
              - name: VERSIONS_EXPORTER_CONFIG_FILE
                value: /config.yaml
            ports:
              - name: metrics
                containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: versions-exporter
  namespace: admin
spec:
  selector:
    app: versions_exporter
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      targetPort: 8083
      protocol: TCP
