---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: versions-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: versions_exporter
        annotations:
          prometheus.io/scrape: "true"
      spec:
        containers:
          - name: versions-exporter
            image: harbor.nuglif.net/nuglif/versions_exporter:0.1.6
            env:
              - name: VERSIONS_EXPORTER_LOGLEVEL
                value: debug
            ports:
              - name: metrics
                containerPort: 8083
        serviceAccountName: versions-exporter
---
kind: Service
apiVersion: v1
metadata:
  name: versions-exporter
spec:
  selector:
    app: versions_exporter
  ports:
  - name: metrics
    port: 8083 
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: versions-exporter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: versions-exporter
rules:
  - apiGroups: [""]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "list"]
---
api: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: versions-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: versions-exporter
subjects:
  - kind: ServiceAccount
    name: versions-exporter
