apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: versions-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
      metadata:
        labels:
          app: versions_exporter
        annotations:
          prometheus.io/scrape: "true"
      spec:
        containers:
          - name: versions-exporter
            image: gg1113/versions_exporter:0.1.6
            env:
              - name: VERSIONS_EXPORTER_LOGLEVEL
                value: debug
            ports:
              - name: metrics
                containerPort: 8083
